version: "3.9"

services:
  cms-dev:
    build:
      context: .
      target: dev
    ports:
      - "3002:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000

  cms-test:
    build:
      context: .
      target: test
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run test:ci

  cms-build:
    build:
      context: .
      target: test
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run build
